config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pessoas#index"

  resources :pessoas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  # Validaçoes
  validates :nome, presence: true, length: { minimum: 1 }
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :cpf, presence: true
  validates :cpf, presence: true, uniqueness: true, cpf: true
  validates :cpf, :cpf => true
  validates :telefone, presence: true, length: { minimum: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController

  def index
    @q = Pessoa.ransack(params[:q])
    @pessoas = @q.result(district: true)
  end

  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
  
  def new 
    @pessoa = Pessoa.new 

    respond_to do |format|
      format.html
    end
  end
  
  def create
    @pessoa = Pessoa.new(pessoa_params)

    #respond_to do |format|

      if @pessoa.save
        #format.html { redirect_to pessoa_url }
        redirect_to @pessoa
      else
        #format.html { render :new }
        render :new, status: :unprocessable_entity
      end
    #end  
  end

  def edit
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
     format.html
    end
  end
  
  def updtae
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|

      if @pessoa.update_attributes(pessoa_params)
        format.html { redirect_to pessoas_url }
        #redirect_to @pessoa
      else
        format.html { render :edit }
        #render :edit, status: :unprocessable_entity  
      end
    end
  end
  
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy
    redirect_to root_path, status: :see_other

    respond_to do |format|
     format.html
    end
  end
  
  private

  def pessoa_params
    params.require(:pessoa).permit(:nome, :email, :cpf, :telefone)    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoFormulario</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <%#= video_tag( # adicionar o video na tela
        'girl.mp4',
        id: 'background',
        autoplay: true,
        loop: true,
        muted: true
      ) 
    %>

    <%= render 'shared/nav' %>
     <div class="container">
    <%= yield %>
    <%= render 'shared/footer' %>    
    </div>
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for @pessoa, html: { class: 'pessoa_search' } do |f| %>
  <%= params[:action].eql?("edit") ? " " : "" %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-white"><%= pluralize(@pessoa.errors.count, "error") %> Não foi possivel salvar Pessoa: </h2>
      <ul class="text-white">
        <% @pessoa.errors.full_messages_for(:nome).each do |message| %>
          <li><%= message %></li>
        <% end %>
        <% @pessoa.errors.full_messages_for(:email).each do |message| %>
          <li><%= message %></li>
        <% end %>
        <% @pessoa.errors.full_messages_for(:cpf).each do |message| %>
          <li><%= message %></li>
        <% end %>
        <% @pessoa.errors.full_messages_for(:telefone).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-lg-4">
    <%= f.label :nome, "Nome:", class: 'text-white' %>
    <%= f.text_field :nome,  class: "form-control" %>
    <% @pessoa.errors.full_messages_for(:nome).each do |message| %>
      <div class="text-white"> <%= message  %> </div>
    <% end %>
  </div>
  <br/>
  <div class="col-lg-4">
    <%= f.label :email, "Email:", class: 'text-white' %>
    <%= f.text_field :email,  class: "form-control" %>
    <% @pessoa.errors.full_messages_for(:email).each do |message| %>
      <div class="text-white"> <%= message  %> </div>
    <% end %>
  </div>
  <br/>
  <div class="col-lg-4">
    <%= f.label :cpf, "CPF:", class: 'text-white' %>
    <%= f.text_field :cpf,  class: "form-control" %>
    <% @pessoa.errors.full_messages_for(:cpf).each do |message| %>
      <div class="text-white"> <%= message  %> </div>
    <% end %>
  </div>
  <br/>
  <div class="col-lg-4">
    <%= f.label :telefone, "Telefone:", class: 'text-white' %>
    <%= f.text_field :telefone,  class: "form-control"%>
    <% @pessoa.errors.full_messages_for(:telefone).each do |message| %>
      <div class="text-white"> <%= message  %> </div>
    <% end %>
  </div>
  <br/>
  <div>
    <%= f.submit "Criar", class: "btn btn-primary" %>
    <%= link_to 'Voltar', pessoas_url, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/pessoas/_search_form.html.erb
<br/>
<%= search_form_for @q, html: { class: "pessoa_search" } do |f| %>
  <div class="row">
    <div class="col-lg-3">
      <%= f.label :nome, "NOME:", class: 'text-white' %>
      <%= f.search_field :nome_cont, class: 'form-control'%>
    </div>

    <div class="col-lg-3">
      <%= f.label :cpf, "CPF:", class: 'text-white' %>
      <%= f.search_field :cpf_cont, class: 'form-control'%>
    </div>

    <div class="col-lg-3">
      <%= f.label :email, "EMAIL:", class: 'text-white' %>
      <%= f.search_field :email_cont, class: 'form-control'%>
    </div>

  </div>
  <br/>
  <div class="col-lg-3">
    <%= f.submit "Busca Avançada", class: 'btn btn-primary text-white' %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editar Cadastro </h1>

<%= render 'pessoas/form' %>

app/views/pessoas/index.html.erb
<br/>
<h1>Lista de Pessoas</h1>
<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <%= render 'search_form' %>      
    </header>
    <% @pessoas.each do |pessoa| %>
      <div class="p-5 mb-2 bg-light rounded-3">
        <div class="container-fluid py-2">
          <div class="row align-items-md-stretch">
            <div class="col-md-5">
              <div class="h-100 p-5 bg-dark border rounded-3 text-white">
                <h2><%= pessoa.nome %></h2>
                <div class="card-body">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to "Mostrar", pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary" %>
                      <%= link_to "Editar", edit_pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary" %>

                      <%= link_to "Deletar", pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary",
                                  method: :delete, 
                                  data: {confirm: "Tem Certeza?"} %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-5">
              <div class="h-100 p-5 text-white bg-dark rounded-3">
                <h2><%= pessoa.nome %></h2>
                <div class="card-body">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to "Mostrar", pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary" %>
                      <%= link_to "Editar", edit_pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary" %>

                      <%= link_to "Deletar", pessoa_path(pessoa), 
                                  class: "btn btn-outline-secondary",
                                  method: :delete, 
                                  data: {confirm: "Tem Certeza?"} %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <br>
    <%= link_to 'Novo Cadastro', new_pessoa_path, class: 'btn btn-primary' %>
  </div>
</main>

app/views/pessoas/new.html.erb
<br/>
<h1>Novo Cadastro</h1>

<%= render 'pessoas/form' %>

app/views/pessoas/show.html.erb
<br/>
<br/>
<div class="row">
  <div class="col-md-12">
    <div class="widget margin-t-md" style="margin-bottom: 15px">
      <div class="widget-header" style="margin-bottom: 15px">
        <div class="widget-title">
          <h1>Dados Cadastro<h1>
        </div>
        <br/>
      </div>
      <br>
      <div class="widget margin-t-md" style="margin-bottom: 15px">
        <br> 
        <div class="text-white">
          <strong>Nome:</strong>
          <%= @pessoa.nome %>
        </div>
        <br>
        <div class="text-white">
          <strong>Email:</strong>
          <%= @pessoa.email %>
        </div>
        <br>
        <div class="text-white">
          <strong>CPF:</strong>
          <%= @pessoa.cpf %>
        </div>
        <br>
        <div class="text-white">
          <strong>Telefone:</strong>
          <%= @pessoa.telefone %>
        </div>
        <br>
      </div>
    </div>  
    <div>
      <%= link_to "Voltar", root_path, class: "btn btn-primary" %> 
    </div>    
  </div>
</div>